# Numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,33,4]])

In [3]:
arr[0,3]

4

In [4]:
arr[0,3]=100

In [5]:
arr

array([[  1,   2,  33, 100]])

# Array creation:conversion from other python structures

In [6]:
listarr=np.array([[1,2,3],[3,4,5],[90,9,90]])

In [7]:
listarr

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [90,  9, 90]])

In [8]:
listarr.dtype

dtype('int32')

In [9]:
listarr.shape

(3, 3)

In [10]:
zeros=np.zeros((3,3))

In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
rng=np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace=np.linspace(0,3,10)

In [15]:
lspace

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [17]:
emp=np.empty((3,3))

In [18]:
emp

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ],
       [2.33333333, 2.66666667, 3.        ]])

In [23]:
emp_like=np.empty_like(lspace)

In [28]:
emp_like

array([1.49079037e-311, 1.72922976e-322, 0.00000000e+000, 0.00000000e+000,
       6.79038653e-313, 1.16095484e-028, 1.47278630e+179, 9.08367237e+223,
       1.16466228e-028, 1.04718130e-142])

In [29]:
ide=np.identity(3)

In [30]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
ide.shape

(3, 3)

In [32]:
arr=np.arange(50)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
arr.reshape(1,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]])

In [35]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [36]:
arr.reshape(0,50)

ValueError: cannot reshape array of size 50 into shape (0,50)

In [37]:
arr.reshape(1,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]])

In [38]:
arr.rave()

AttributeError: 'numpy.ndarray' object has no attribute 'rave'

In [39]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
x=[[1,2,4],[3,4,5],[6,7,8]]

In [41]:
arr=np.array(x)

In [42]:
arr

array([[1, 2, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
ar.sum(axis=0)

NameError: name 'ar' is not defined

In [44]:
arr.sum(axis=0)

array([10, 13, 17])

In [45]:
arr.sum(axis=1)

array([ 7, 12, 21])

In [46]:
arr.T

array([[1, 3, 6],
       [2, 4, 7],
       [4, 5, 8]])

In [47]:
ar.flat

NameError: name 'ar' is not defined

In [48]:
arr.flat

In [50]:
for i in arr.flat:
    print(i)

1
2
4
3
4
5
6
7
8


In [51]:
arr.ndim

2

In [52]:
array=np.array([[1,2,3,45,6]])

In [77]:
array.argmax()

3

In [54]:
array.argmin()

0

In [55]:
array.argsort()

array([[0, 1, 2, 4, 3]], dtype=int64)

In [56]:
arr

array([[1, 2, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
arr.argmax()

8

In [59]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [60]:
arr.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [61]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [62]:
arr.reshape(2,2)

ValueError: cannot reshape array of size 9 into shape (2,2)

In [63]:
arr.rehshape(1,9)

AttributeError: 'numpy.ndarray' object has no attribute 'rehshape'

In [64]:
arr.reshape(9,1)

array([[1],
       [2],
       [4],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [65]:
arr.reshape(1,9)

array([[1, 2, 4, 3, 4, 5, 6, 7, 8]])

In [67]:
arr2=np.array([[0, 1, 2],
       [4, 1, 2],
       [3, 1, 2]])

In [68]:
arr1+arr2

NameError: name 'arr1' is not defined

In [69]:
arr+arr2

array([[ 1,  3,  6],
       [ 7,  5,  7],
       [ 9,  8, 10]])

In [70]:
arr*arr2

array([[ 0,  2,  8],
       [12,  4, 10],
       [18,  7, 16]])

In [71]:
np.sqrt(arr)

array([[1.        , 1.41421356, 2.        ],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [72]:
np.square(arr)

array([[ 1,  4, 16],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [73]:
arr.sum

<function ndarray.sum>

In [74]:
arr.sum()

40

In [75]:
arr.max()

8

In [78]:
np.where(arr>5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [79]:
arr

array([[1, 2, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
np.where(arr>5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [81]:
arr.dtype

dtype('int32')

In [82]:
np.count_nonzero(arr)

9

In [83]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [84]:
import sys

In [85]:
py_ar=[0,4,5,67]

In [86]:
sys.getsizeof(1)*len(py_ar)

112

In [87]:
np_ar=np.array(py_ar)

In [89]:
np_ar.itemsize*np_ar.size

16